// Static list of NTS genres with 500+ episodes, sorted by episode count.
// Used to populate the Search tab's genre picker.

/// (api_id, display_name) pairs for genres with substantial episode counts.
pub const TOP_GENRES: &[(&str, &str)] = &[
    ("housetechno", "House / Techno"),
    ("hiphoprandb", "Hip-Hop / R'n'B"),
    ("postpunkwave", "Post Punk / New Wave"),
    ("soulrhythm", "Soul / Rhythm & Blues"),
    ("ambientnewage", "Ambient / New Age"),
    ("rock", "Rock"),
    ("housetechno-house", "House"),
    ("electronicadowntempo", "Electronica / Downtempo"),
    ("ambientnewage-ambient", "Ambient"),
    ("other", "Other"),
    ("avantgarde", "Avant Garde"),
    ("jazz", "Jazz"),
    ("housetechno-techno", "Techno"),
    ("newclub", "New Club"),
    ("hiphoprandb-hiphop", "Hip Hop"),
    ("altrockpunk", "Alternative Rock / Punk"),
    ("soulrhythm-soul", "Soul"),
    ("discoboogie", "Disco / Boogie"),
    ("electronicadowntempo-electronica", "Electronica"),
    ("avantgarde-experimental", "Experimental"),
    ("caribbean", "Caribbean"),
    ("rock-folk", "Folk"),
    ("ukdance", "UK Dance / Grime"),
    ("newclub-club", "Club"),
    ("hiphoprandb-rnb", "RNB"),
    ("rock-psychedelic-rock", "Psychedelic Rock"),
    ("postpunkwave-synthpop", "Synth Pop"),
    ("postpunkwave-postpunk", "Post Punk"),
    ("discoboogie-classicdisco", "Classic Disco"),
    ("postpunkwave-newwave", "New Wave"),
    ("classicalopera", "Classical / Opera"),
    ("soulrhythm-funk", "Funk"),
    ("caribbean-dub", "Dub"),
    ("altrockpunk-indie", "Indie Rock"),
    ("postpunkwave-minimalsynth", "Minimal Synth"),
    ("hiphoprandb-trap", "Trap"),
    ("housetechno-electro", "Electro"),
    ("discoboogie-boogie", "Boogie"),
    ("africanmiddleeast", "African / Middle Eastern"),
    ("postpunkwave-industrial", "Industrial"),
    ("housetechno-house-deephouse", "Deep House"),
    ("newclub-bass", "Bass"),
    ("electronicadowntempo-beats", "Beats"),
    ("jazz-souljazz", "Soul Jazz"),
    ("housetechno-techno-leftfieldtechno", "Leftfield Techno"),
    ("jazz-straightjazz", "Straight Jazz"),
    ("other-leftfield-pop", "Leftfield Pop"),
    ("avantgarde-drone", "Drone"),
    ("caribbean-reggae", "Reggae"),
    ("jazz-jazzfusion", "Jazz Fusion"),
    ("latinbrazil", "Latin / Brazilian"),
    ("caribbean-dancehall", "Dancehall"),
    ("housetechno-house-leftfieldhouse", "Leftfield House"),
    ("discoboogie-leftfielddisco", "Leftfield Disco"),
    ("other-pop", "Pop"),
    ("ukdance-grime", "Grime"),
    ("jazz-contemporaryjazz", "Contemporary Jazz"),
    ("altrockpunk-dreampop", "Dream Pop"),
    ("avantgarde-noise", "Noise"),
    ("asia", "Asia"),
    ("ambientnewage-newage", "New Age"),
    ("altrockpunk-punk", "Punk"),
    ("jazz-freejazz", "Free Jazz"),
    ("other-talk", "Talk"),
    ("housetechno-techno-ambienttechno", "Ambient Techno"),
    ("other-soundtrack", "Soundtrack"),
    ("metal", "Metal"),
    ("classicalopera-modern-classical", "Modern Classical"),
    ("housetechno-breaks", "Breaks"),
    ("avantgarde-musiqueconcrete", "Musique Concrete"),
    ("jazz-spiritualjazz", "Spiritual Jazz"),
    ("altrockpunk-artrock", "Art Rock"),
    ("newclub-footwork", "Footwork"),
    ("housetechno-acid", "Acid"),
    ("classicalopera-minimalism", "Minimalism"),
    ("ukdance-jungle", "Jungle"),
    ("classicalopera-classical", "Classical"),
    ("rock-classicrock", "Classic Rock"),
    ("ukdance-ukgarage", "Garage"),
    ("ambientnewage-kosmiche", "Kosmische"),
    ("housetechno-brokenbeat", "Broken Beat"),
    ("altrockpunk-noiserock", "Noise Rock"),
    ("africanmiddleeast-afrobeat", "Afrobeat"),
    ("rock-psychadelicfolk", "Psychedelic Folk"),
    ("ukdance-drumandbass", "Drum & Bass"),
    ("rock-soft-rock", "Soft Rock"),
    ("postpunkwave-ebm", "EBM"),
    ("discoboogie-italo", "Italo"),
    ("newclub-afrobeats", "Afrobeats"),
    ("other-spoken-word", "Spoken Word"),
    ("altrockpunk-garagerock", "Garage Rock"),
    ("hiphoprandb-uk-drill", "Drill"),
    ("hiphoprandb-rap", "Rap"),
    ("altrockpunk-shoegaze", "Shoegaze"),
    ("latinbrazil-latinjazz", "Latin Jazz"),
    ("other-live-performance", "Live Performance"),
    ("housetechno-minimal", "Minimal"),
    ("soulrhythm-slowjams", "Slow Jams"),
    ("hiphoprandb-classichiphop", "Classic Hip Hop"),
    ("housetechno-house-balearichouse", "Balearic House"),
    ("housetechno-trance", "Trance"),
    ("metal-heavymetal", "Heavy Metal"),
    ("newclub-reggaeton", "Reggaeton"),
    ("rock-progrock", "Prog Rock"),
    ("electronicadowntempo-glitch", "Glitch"),
    ("avantgarde-darkambient", "Dark Ambient"),
    ("ambientnewage-forthworld", "Fourth World"),
    ("rock-country", "Country"),
    ("hiphoprandb-experimentalhiphop", "Experimental Hip Hop"),
    ("soulrhythm-rhythmandblues", "Rhythm & Blues"),
    ("housetechno-techno-dubtechno", "Dub Techno"),
    ("electronicadowntempo-trip-hop", "Trip Hop"),
    ("altrockpunk-postrock", "Post Rock"),
    ("other-interview", "Interview"),
    ("rock-krautrock", "Krautrock"),
    ("jazz-modal", "Modal"),
    ("jazz-ambientjazz", "Ambient Jazz"),
    ("housetechno-house-detroithouse", "Detroit House"),
    ("asia-jpop", "J-Pop"),
    ("jazz-jazzrock", "Jazz Rock"),
    ("hiphoprandb-ganstarap", "Gangsta Rap"),
];
